### ISSUE TITLE
Internal testing milestone todos

### ISSUE THREAD

**Issue by losman0s** [mrgnlabs/marginfi-v2#33]
- [x] get consensus on b/l/w/r ambiguity + difficulty to compare rates due to toggle -> do nothing for now, ship existing design, wait for feedback before considering change
- [ ] ~contract needs flag to explicitly request borrowing (default: repay only)~ postponed
- [ ] create separate pool w/ many banks to test liq bot
- [x] wire max lend/withdraw/repay/borrow
- [x] cap input box to max lend/withdraw/repay/borrow
- [ ] ~identify + add missing account health info~ postponed
- [x] review pool metrics
- [x] wire pool metrics
- [x] supplying/borrowing sections headers have wrong font
- [x] asset-specific interest rate need checking
- [ ] ~extend tx confirmation timeout~ postponed
- [x] format all numbers (usd value, percentage, etc)
- [x] net APY needs checking or removing
