### ISSUE TITLE
Private alpha milestone todos

### ISSUE THREAD

**Issue by losman0s** [mrgnlabs/marginfi-v2#34]
- [x] complete in-house testing
- [ ] search & destroy accounting bug
- [x] implement password protection on production UI
- [x] deploy mainnet program
- [x] create staging group + quick tests
- [x] create production group + configure (create banks, choose parameters)
- [ ] fund production banks
